### ISSUE TITLE
x-errors in multifit

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#103]
x-erros in multifit do not appear on graphs, although the appear
to be taken into account in the fit

code:
 multi_fit.add_simple_error(sigU, 'all', axis='x')   # shared error on x axis
 
 x-error bars are only shown on plots if set separately for fit 0 and 1:
 multi_fit.add_simple_error(sigU, 0, axis='x')  
 multi_fit.add_simple_error(sigU, 1, axis='x') 
The fit result in this case is, however, different; it is not clear whether the errors
are treated as fully correlated in this case.

The same behavior is visible in the example in kafe2/examples/102_multifit/multifit.py

**Comment by Citiroller** [comment]
Looking through the code there seem to be two possibilities on how to fix this.
1. When adding a shared error, the error has to be added to the singel fits as well, so the Plotter picks up the error for both fits. This could change the results of the fit though as the errors might be taken into account twice.
2. Changing the Plot class to check if a Multifit contains a shared error. Then deepcopy the single fits in order to not change them and add the shared x_error as error source in both fits, the start plotting.

Personally I would prefer option 1 as we can use the already present strucutres. but I'm not sure if that will change the values of the fit results.
@JohannesGaessler implemented the multifit. Maybe he has a good idea on how to fix this issue. I would need to wrap my head around the existing codes which would take some time.

**Comment by JohannesGaessler** [comment]
I will take care of it.
