### ISSUE TITLE
Wildcard imports in __init__.py files

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#107]
The wildcard imports in all `__init__.py` cause all classes to be listed during code completion and to be visible to the outside world.
But not all classes are needed by the end user or developers using kafe2. For example the ParametricModelBaseMixin or kafe2.core.fitter.nexus.Alias class does not need to be present at the top level.
Currently an import like import `kafe2.Alias` is possible. In my opinion this should be reduced to at least a `import kafe2.core.Alias as Alias` or a `kafe2.core.fitter.nexus.Alias as Alias`.

For this we would need to replace all the wildcard imports in the init files with curated imports.

**Comment by dsavoiu** [comment]
I think this issue is better solved by consistently defining the `__all__` variable
in the imported submodules, rather than explicitly importing things in `__init__.py`.
It exists precisely for curating wildcard imports and should be understood by most modern IDEs or code completion tools.

The reason wildcard imports are used in `__init__.py` files is to avoid a tight coupling to the submodule API. Instead each submodule decides what is exported via `__all__`, and just passed these exports on to modules higher up in the hierarchy via `import *`.
If no wildcards are used, exporting a symbol at the top level would either require importing symbols from a submodule multiple levels below the current one (`import  sub1.sub2.X`), or having an explicit `import X` in every `__init__.py` along the way, both of which are unnecessarily verbose and
negatively impact maintainability. Ideally, `__init__.py` files should only have to be modified when a new submodule is added, from which functionality should be exposed to the outside.

Concerning making classes available at the top-level, I think something like `from kafe2 import XYFit` is vastly preferable to more verbose alternatives, since the `XYFit` class is a central component of *kafe2*. However, this is not the case for `kafe2.Alias`, which should indeed not be present in the top-level module API. Most probably, it is being imported by a submodule somewhere and reexported from there due to a missing `__all__`.

**Comment by Citiroller** [comment]
I'll go through the `__all__` definitions and make sure they are used properly and try to get the desired verbosity for lower level modules like `Alias` while maintaining the top level definitions for all standard use cases.

**Comment by Citiroller** [comment]
Most issues were fixed by adding some missing `__all__` variables in 98abb0c328d64d2bb833e23cea5b07f680518be5.

When going further we should define a coherent way of handling this.
My ideas would be:
* All fits and fit exceptions
* All data container and exceptions
* Fit:
  * Representation
    * Everything regarding representation, ideally the user uses the supplied functions from the fit classes
  * For each fit type:
    * ParametricModel
    * CostFunctions
    * Plot Adapter
* Core
  * Everything from core at this level?
* Config
  * All config stuff
* Plot
* ContoursProfiler

There are still some missing classes like Ensembles.
