### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by ralfulrich** [dsavoiu/kafe2#122]
This is just a "cry for help" since I cannot figure out how to get easy access to parameter estimates and their uncertainties, covariances, thus, I have this code:

```
pre_fit_data = XYContainer(x_data=x_data, y_data=y_data_logistic)
pre_fit_data.add_error(axis='y', err_val = [v*0.01 for v in y_data_logistic] )
pre_fit = XYFit(pre_fit_data)
pre_fit.do_fit()
```

How do I get the values of the parameter estimates and their uncertainties/covariances?
I expected something like:
```
...
minimum = pre_fit.do_fit()
print ("Cost function at minimum {}".format(minimum.cost()))
print ("Parameter a {} +- {}".format(minimum.parameter(0), minimum.uncertainty(0)))
print ("Parameter b {} +- {}".format(minimum.parameter(1), minimum.uncertainty(1)))
``` 

But could not figure out how to do this given the available examples and documentation. 

I would appreciate very much to get an example from the experts...

**Comment by ralfulrich** [comment]
Thanks! This already solved my main problem. But I really suggest to add the dict as return from the do_fit routine, too.

**Comment by JohannesGaessler** [comment]
`do_fit` now returns a dictionary with the fit results.
Calculation of asymmetric parameter errors can be requested with `asymmetric_parameter_errors=True`.
I've also followed the suggestion made in https://github.com/dsavoiu/kafe2/issues/123 regarding data types: parameter values, (asymmetric) parameter uncertainties are now of type OrderedDict instead of list.
