### ISSUE TITLE
API inconsistencies

### ISSUE THREAD

**Issue by ralfulrich** [dsavoiu/kafe2#123]
**Describe the bug**

Functions use different argument names for the same quantiie, e.g.
 
` fix_parameter(name, value=None)'
vs
' limit_parameter(par_name, par_limits)' 

**Expected behavior**

Consistent and concise names should be used instead: 

` fix_parameter(name, value=None)'
vs
' limit_parameter(name, par_limits)'

**Comment by Citiroller** [comment]
Are there any more examples? The API should be at a good level when leaving beta state.
If you find more issue like this please let us know.

**Comment by ralfulrich** [comment]
If I find more, I let you know, but so far I have by far not touched all functionality of kafe2. And unfortunately I won't have time for a full study soon. But thanks for caring and taking care! Maybe a quite simple text search on your API will be very effective. 

There are a few more things I noticed: 

- [ ] The API to access particular "parameters" is mostly a string "name", which I think is very nice. However, in the "get_results_dict" the "parameter_values" is just an array, which leads to code like this: `fit3.fix_parameter(name='ymax', value=fit3_minimum['parameter_values'][0])` but it would be much safer (and also more readable) to have `fit3.fix_parameter(name='ymax', value=fit3_minimum['parameter_values']['ymax'])`
- [ ] `release_parameter(par_name='K')` should be `release_parameter(name='K')`
- [ ] `set_poi_values(fit3_minimum['parameter_values'])` should of course accept the same format as `get_results_dict` returns, see above. 
- [ ] `set_poi_values` should be renamed. POI is an abbreviation and not needed here. Maybe `set_parameter_values` would be a good alternative
- [ ] I am not sure about `limit_parameter` but I think to explicitly have `lower_bound` and `upper_bound` is much better than having a tuple `par_limits`

**Comment by Citiroller** [comment]
Thank you. I'll look into it and discuss some proposed changes with the team.

**Comment by JohannesGaessler** [comment]
`FitBase.to_file` has a parameter named *calculate_asymmetric_errors* instead of *asymmetric_parameter_errors*.

**Comment by JohannesGaessler** [comment]
>set_poi_values should be renamed. POI is an abbreviation and not needed here. Maybe set_parameter_values would be a good alternative

The method `FitBase.set_parameter_values` aready exists.
Semantically it is the same as `XYFit.set_poi_values` for most applications.
However, when nuisance parameters are introduced their semantics differ because parameters of interest are a subset of all parameters.
(A bachelor student implemented nuisance parameters for XYFit in the past but their implementation was broken due to internal changes. Nuisance parameters are therefore currently not supported but will be re-implemented in the future)

**Comment by Citiroller** [comment]
I've updated the keywords of fix, release. limit and unlimit in f83212f53b37ffb710f2f882e2995b9793eb76cf. This should be fine now.
```
results = fit1.do_fit()
fit2.set_parameter_values(**results['parameter_values'])
```
should be working since a621312c2b2d79592d7cdd9147b54513e2ddc9c8.

**Comment by ralfulrich** [comment]
Ok. I missed the `set_parameter_values`, which is perfectly fine. The `poi` is then of course fine, if proper examples and documentation is provided later.

**Comment by Citiroller** [comment]
Using indices is not required since a621312, as `do_fit` returns a dict for parameter values. So
```
fit3_minimum = fit2.do_fit()
fit3.fix_parameter(name='ymax', value=fit3_minimum['parameter_values']['ymax'])
```
is perfectly fine.
The only remaining issue would be lower_bound and upper_bound for parameter limits instead of a tuple. But I'm not sure if that would be a better alternative. We always have one dimensional parameters (for now) and the limits always have to be two floats. A tuple[float, float], as the docstring describes is perfectly fine. This would, imo, only be reasonable when #124 is introduced.
Without #124 there would always be an issue when there is no lower_bound specified. So I think that a tuple is a better option.

**Comment by ralfulrich** [comment]
Thanks for all the work. The "bounds" tuple is really OK, if the API documentation is available and some examples are provided at some point. So this was basically a suggestion to think about. I would be fine to keep this.

**Comment by Citiroller** [comment]
Alright, closing this issue now. I'm transferring the parameter limits to #124
