### ISSUE TITLE
Add label modifiers

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#31]
By default the x and y labels are `$x$` and `$y$` as set in the default configuration. The user should be able to easily modify those labels eg. to `Time $t$ [s]`.
Generally: `quantity $symbol$ [unit]` as in kafe1.
In kafe1 this was done when creating the dataset `class kafe.dataset.Dataset(data=None, title='Untitled Dataset', axis_labels=['x', 'y'], axis_units=['', ''], **kwargs)` where it required the user to set `quantity $symbol$` as `axis_label` and `unit`. The parenthesis around the unit were added by the program.

`model 0` and `data 0` on the right side of the plot should be nameable as well .

To Do:
- [x] add function to modify x- and y-labels (#32) needs to be reworked for the new Plotting Class
- [x] add function to modify the name of `model` and `data`

Questions:
- where to set the x- and y-labels? In the `XYContainer` and get it from the container object when plotting? --> Yes
- modify `data 0` similarly to kafe1 by setting a `title` in the `XYContainer`?
- modify `model 0` by specifying a model name in the `XYFit` object?

**Comment by Citiroller** [comment]
Also physicians like to use greek letters for lots of physical quantities. So we need to check if its possible to display a fit function like `$\phi(\omega;a) = a*\omega$`.
Of course this is a simple linear function `$y(x;a) = a*x$` and probably not worth the effort to implement this, but physicians love to use greek letters.

**Comment by JohannesGaessler** [comment]
>where to set the x- and y-labels? In the XYContainer and get it from the container object when plotting?

I think we should specify labels via `XYPlot`.
I don't know about kafe1 but in kafe2 you can create a plot object from more than one fit object (the fits are then shown in the same plot).
If the label names were stored in fit objects it would then be ambiguous as to which labels to use.

>modify data 0 similarly to kafe1 by setting a title in the XYContainer?
>modify model 0 by specifying a model name in the XYFit object?

Since these vary by fit object it would make sense to store them in fit objects.

While the above considerations would be fine in terms of functionality we might also need to think about useability; If cosmetic fit properties are being specified in a dozen different places it will be a pain to use.
We should probably have a more detailed discussion about this.

>Also physicians like to use greek letters for lots of physical quantities.

`matplotlib` natively supports LaTeX, so using special characters as labels should not be a problem.

**Comment by Citiroller** [comment]
x- and y-labels are implemented now. See PR #32

**Comment by Citiroller** [comment]
This needs to be updated to the new plotting interface! Duplicate of #76

**Comment by Citiroller** [comment]
Should the model and model error labels default to the name of the model function?
I think this is a good idea as the (parametric) model function is shown in the plot. Then there would be no need for the defaults in the config as well.
I would still implement a way for the user to override the labels.
