### ISSUE TITLE
x and y-labels in kafe2go

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#34]
In kafe2go the yaml file is read with `_fit = FitBase.from_file(_filename, format=_input_format)` at line 62, which creates a fit object. When we want to add labels to kafe2go there are 2 possibilities:

1. When generating the plot with `_plot = _fit.generate_plot()` with kwargs or setting it later with `_plot.x_label = "some string"`, but this requires the file to be read again.
2. Store the labels in the fit object when calling `_fit = FitBase.from_file(_filename, format=_input_format)` and then set the labels of the plot when calling `_plot = _fit.generate_plot()`. This requires the labels to be stored in the fit class as well, but the file is only read once.

Some feedback on how to implement this is appreciated @JohannesGaessler

**Comment by JohannesGaessler** [comment]
Option 1 is probably more difficult than what you imagine it to be.
kafe2go is designed to throw errors when given an unexpected/unused keyword.
This is because it's very likely that there is a difference between what the user typed and what the user meant in such scenarios and it's better to give instantaneous feedback than to have the user discover the mistake later on.
However, this also means that you can't just specify additional keywords in the input file that are not being used in the construction of the fit object; You would have to manually whitelist which keywords should be allowed in the input file.
Another, more technical problem would be that this option would limit you to sources that can be read more than once; It would work fine for files but depending on the protocol it would not work for a network connection (or you would need to send the same file twice over the network).

Because of this I think Option 2 is preferable.
I would suggest that you don't store the labels specifically, but that you store the leftover yaml document as a dictionary in the fit object and then use that dictionary to set the plot properties.
Keep in mind that extra/unexpected keywords should still throw an error.
I think the best way to implement this would be to pop the relevant plot keywords from the fit yaml document during the construction of the fit object inside the yaml reader.
If there are keywords that aren't being popped the yaml reader will throw an error.

**Comment by dsavoiu** [comment]
Another possibility is to simply add command-line arguments to `kafe2go` for setting the *x* and *y* labels, but I think it is better to have this information in the YAML file.

It seems to me that option 2 is indeed preferable, at least for the moment. It does, however, have the somewhat unpleasant side effect of storing information in the `Fit` object that is only relevant to the `Plot`.

As far as I can tell, there is no way to fully avoid this in the current implementation of `kafe2go`, since the deserialization is done in a single call to `FitBase.from_file`, which then consumes the entire YAML document.

For the current scope of `kafe2go`, this is quite acceptable. However, assuming that in a future update we would like to allow users to customize calls to "algorithm classes" that operate on `Fits` (i.e. things like `Plot` and `ContoursProfiler`) via YAML content, one would need to store the relevant keyword in the `Fit` object first. Moreover, `FitBase.from_file` would need to pre-validate (and pop) keywords intended for potentially many other such *algorithm classes*, when this should really be left to the classes themselves.

**Comment by JohannesGaessler** [comment]
I thought about the problem some more.
I think an elegant solution might be found by modifying the behavior yaml reader objects show when presented with extra keywords.
Currently the `_convert_yaml_doc_to_object` method pops the relevant keywords and returns a kafe object and a leftover yaml document.
If the leftover yaml document is not empty an error is thrown.
However, you could allow subclasses of the base reader class to specify keywords that when left over do not cause an error.
The leftover yaml doc could then be passed on to the kafe2go script and be processed there.

The problem with this approach is that it would need to be context sensitive though.
If a fit is being read in from a file inside a regular python script the allowed leftover keywords (None) should be different than when a fit is read in inside the kafe2go script (xlabel, ylabel, ...).
Then you would either have to add a kwarg to the user-exposed from_file method or directly use the reader classes in the kafe2g0 script.

**Comment by Citiroller** [comment]
This is a good idea. As you said there's the problem with the context sensitivity.
Another solution - which requires more work but would be modular - is to outsource a function which converts files to dicts (essentially what the PyYAML package does). This function could then be built upon to support more file formats and/or special cases.
With `kafe2go` we have an issue with the namespaces. There are no seperate `plot:`, `fit:` and `dataset:` keys. But I think in `kafe2go` we could try to generate the top level object (a plot and/or contours) and all the other necessary objects with the leftover keys. If there are unused keys in the end kafe2go would need to throw an error.
This implementation requires a `kafe2go_from_file()` function which could return a `plot` (and a `fit` and a `dataset`) object. And each class would need it's own `class_from_dict()` and `class_from_file()` function and counterparts to import and export those in normal use (which they already have).

> The problem with this approach is that it would need to be context sensitive though.
If a fit is being read in from a file inside a regular python script the allowed leftover keywords (none) should be different than when a fit is read in inside the kafe2go script (xlabel, ylabel, ...).
Then you would either have to add a kwarg to the user-exposed from_file method or directly use the reader classes in the kafe2g0 script.

This context sensitivity can then be handled by the `read_from_file()` implementations inside the classes (no leftover keys) and the detached `kafe2go_from_file()` (no leftover keys after generating a `plot`, `fit` and `dataset` object). So the `read_from_file()` fubctions throw errors and the `class_from_dict()` functions throw no errors and return the class and the leftover keys.

This restructuring of the data handling should be a long term goal and needs some more communication and discussion.

**Comment by Citiroller** [comment]
#83 added akfe2go functionality
Use the following keywords
* `label` for dataset label
* `x_label` for x-axis label
* `y_label` for y-axis label
The above are for each dataset
* `model_label` for model label
The above is for the parametric model
