### ISSUE TITLE
access to minimizer debug output

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#81]
access to the output of the minimizer is needed as an option to be able to debug non-converging fits

**Comment by Citiroller** [comment]
This is now possible for iminuit since b864dfca.
Scipy does not seem to have such a feature
To enable logging, import the python logging module and set a logging level.
```
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
```
The default logging level WARNING will use the iminuit log_level 0 (quiet).
The logging level INFO will use the use the iminuit log_level 1 (normal).
The logging level DEBUG will use the use the iminuit log_level 2 (paranoid).
Everything below DEBUG e.g. DEBUG-1 will sue the maximum iminuit logging level 3 (really paranoid).
Please be aware, that the logging level DEBUG will also enable debugging for matplotlib. This is no problem as long as no plots are created. If a plot is created matplotlib will spam debug information.

**Comment by Citiroller** [comment]
I'm leaving this issue open as this information has to be added to the documentation.

**Comment by Citiroller** [comment]
Moved documentation updates to one single issue, closing this one.
