### ISSUE TITLE
@abstractproperty with Py2 and Py3

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#82]
Since Python 3.3 the decorator `@abc.abstractproperty` is deprecated. Instead the usage of `@property` with `@abc.abstractmethod` is recommended.
This, however, is not supported with Python 2.7.
The code currently contains both options. This behavior should be unified.

One possible solution is to add a new decorator like this:
```
def compatibleabstractproperty(func):

    if sys.version_info > (3, 3):             
        return property(abstractmethod(func))
    else:
        return abstractproperty(func)
```
or we could stick to the deprecated `@abc.abstractproperty`.
See https://stackoverflow.com/questions/5960337/how-to-create-abstract-properties-in-python-abstract-classes for more details.

@dsavoiu and @JohannesGaessler, whats your opinion on this matter?

**Comment by JohannesGaessler** [comment]
First of all, the OP in StackOverflow page you linked is confused about what abstract classes are.
He thinks that `Base_1` should raise an error because it does not implement the name property.
However, because the class specifies that it is also an abstract class via ABCMeta it does not have to implement the name property.
The bug described by the other people in the thread is that in Python 2 using a combination of `@property` and `@abstractmethod` will not raise an error when an abstract property is not defined in a non-abstract sub-class.

However, as long as we run unit tests with both Python 2 and Python 3 this is not a problem.
We will catch any unimplemented abstract properties because it will raise an error when we test with Python 3.
I would therefore suggest that we use a combination of `@property` and `@abstractmethod`.

**Comment by Citiroller** [comment]
Using `@property` and `@abstractmethod` is a good idea, since we're testing with both, Python 2 and 3.
Additionally this prevents issues if we might drop Python 2 support in the future.

I'll take care of this issue soon and replace all `@abstractproperty` asap.
