### ISSUE TITLE
fixing paramter in multifit does not work

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#96]
in ultifit example, tried both 
# fix reference temperature to 20°C
t_ref = 20.

fit_1.fix_parameter('p0', t_ref)
and
multi_fit.fix_parameter('p0', t_ref)

Parameter was listed as "fixed", but in fact was still minimized and
 also showed up in covariance matrix

**Comment by Citiroller** [comment]
When fixing a parameter in a multifit please use `multi_fit.fix_parameter('p0', t_ref)`. Fixing a parameter for a singular fit inside a multifit might cause unexpected behavior.

Fixed parameters always show up in the covariance matrix. Although every entry in their row and column is 0 and they are indeed fixed. This is also the case for singular fits.
If this should be changed, please open another bug report.
Fixing parameters can be best tested for using highly different values than the fit results. E.g. `t_ref=15` in this case. This will change the first fit in the multifit example drastically.

When fixing and releasing parameters the formatters of the single fits are updated correctly since f9c8ca1.
